Cray-HPE/cray-sysmgmt-health

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/smartmon/smartmon.json, kubernetes/cray-sysmgmt-health/templates/prometheus/dhcp-kea/kea-dhcp-alerts.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/node_exporter-smartmon/daemonset.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/node_exporter-smartmon/smartmon-alerts.yaml, kubernetes/cray-sysmgmt-health/values.yaml
cray-sysmgmt-health : Enable smart metrics on k8s nodes using SMARTMON
Management nodes should sample SMART data and publish to Prometheus for k8s nodes
Generate alerts using smart data for k8s nodes
NOTE FOR RELEASE BRANCHES: YOU NO LONGER NEED TO UPDATE THE .version VERSION ON EVERY PR IF THE PR DOES NOT …
=> CASMMON-72, CASMMON-101, CASMMON-100 : Enable SMART metrics, alerts and grafana dashboard for k8s nodes

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/patch-node-exporter/configmap.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/patch-node-exporter/patch-nodeexporter-alerts-job.yaml
cray-sysmgmt-health : NodeFilesystemAlmostOutOfSpace alerts should be alerting when K8s is going to evict pods
NOTE FOR RELEASE BRANCHES: YOU NO LONGER NEED TO UPDATE THE .version VERSION ON EVERY PR IF THE PR DOES NOT CHANGE THE CONTENTS OF THE GENERATED CONTAINER IMAGE. IF YOU DO UPDATE .version, YOU ALSO NEED …
=> CASMMON-103:NodeFilesystemAlmostOutOfSpace alerts should be alerting when K8s is going to evict pods

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/istio/istio-alerts.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/patch-node-exporter/configmap.yaml, kubernetes/cray-sysmgmt-health/values.yaml
cray-sysmgmt-health : need prometheus alert for istio returning only 503's
NOTE FOR RELEASE BRANCHES: YOU NO LONGER NEED TO UPDATE THE .version VERSION ON EVERY PR IF THE PR DOES NOT CHANGE THE CONTENTS OF THE GENERATED CONTAINER IMAGE. IF YOU DO UPDATE .version, YOU ALSO NEED TO UPDATE THE Chart.yaml VERSION …
=> CASMINST-3537:need prometheus alert for istio returning only 503

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/disk-space/disk-space.yaml, kubernetes/cray-sysmgmt-health/values.yaml
Alert when /var/lib/containerd full
cray-sysmgmt-health : https://connect.us.cray.com/jira/browse/CASMMON-57
NOTE FOR RELEASE BRANCHES: YOU NO LONGER NEED TO UPDATE THE .version VERSION ON EVERY PR IF THE PR DOES NOT CHANGE THE CONTENTS OF THE GENERATED CONTAINER IMAGE. IF YOU DO UPDATE .version, YOU ALSO NEED TO UPDATE THE Chart.yaml VERSION (if you have one). IF YOU ARE ONLY …
=> CASMMON-57:Alert when /var/lib/containerd full

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/grafana/dashboards/dhcp-kea/keadhcp.yaml, kubernetes/cray-sysmgmt-health/templates/grafana/dashboards/postgresql/postgresql.yaml, kubernetes/cray-sysmgmt-health/templates/grafterm/configmap.yaml, kubernetes/cray-sysmgmt-health/templates/grafterm/deployment.yaml, kubernetes/cray-sysmgmt-health/templates/node-exporter/post-install.yaml, kubernetes/cray-sysmgmt-health/templates/node-exporter/rbac.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/ceph/ceph-prometheus-alert.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/ceph/ceph-prometheus.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/dhcp-kea/kea-dhcp-alerts.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/dhcp-kea/monitors/cray-dhcp-kea.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/disk-space/disk-space.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/mdraid/mdraid-prometheus-alert.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/monitors/patch-service-monitors-job.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/monitors/service-monitor.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/node_exporter-smartmon/daemonset.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/node_exporter-smartmon/smartmon-alerts.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/patch-node-exporter/patch-nodeexporter-alerts-job.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/postgres/monitors/cray-rm-pals-postgres.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/postgres/monitors/cray-sls-postgres.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/postgres/monitors/cray-smd-postgres.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/postgres/monitors/gitea-vcs-postgres.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/postgres/monitors/keycloak-postgres.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/postgres/monitors/sma-postgres-cluster.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/postgres/monitors/spire-postgres-cluster.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/postgres/postgres-exporter-service.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/postgres/postgres-prometheus-alert.yaml, kubernetes/cray-sysmgmt-health/values.yaml
Clean up license header changes.
* Remove {{ /* \<LICENSE\> */ }} that existed prior to license-check fix
* Change {{- \/* ... \*\/ -}} to {{\/\* ... \*\/}} in existing code where this resulted in the next line being commented out (e.g. #apiVersion, #kind)
* Keep the license header added by the license-check (which uses # to start the line)
* Update the chart version to prepare to release the cray-sysmgmt-health chart for this change
* Resolves [CASMINST-3833](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3833)
* Change will also be needed in NA
* Future work required by NA
* Documentation changes required in NA
* Merge with/before/after NA
vshasta
* …
=> CASMINST-3833 : BREAK/FIX: apiVersion not set chart=cray-sysmgmt-health

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/grafterm_dashboards/critical_services_dashboard.json, kubernetes/cray-sysmgmt-health/values.yaml
Snyk scan was reporting 3 criticals and 14 highs for the cray-grafterm image.
To resolve this we are using the golang:1.17.3-alpine3.13 version for the grafterm.
https://github.com/Cray-HPE/container-images/pull/383 (merged)
https://github.com/Cray-HPE/cray-grafterm/pull/2 (merged)
* Resolves 
[CASMPET-5269](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5269)
* Change will also be needed in 
Need to create tag for 1.2 branch after merging this PR
* Future work required:
Bump the grafterm and sysmgmt-heatlh version in csm product repo.
* Documentation changes required
None
* Merge with/before/after
None
Done
Gamora
Able to get the Grafterm graphs
None
=> CASMPET-5269: fix snyk issue by bumping the version

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
Followed the objectives in CASMPET-5237.
This image has immutable upstream tag, and it is not updated with latest security patches. 
To avoid that, use patched and signed version of this image, delivered via container-images repo. 
For that, image needs to be added to container-images repo and reference in 
cray-sysmgmt-health chart changed to point to this version.
https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5237
https://github.com/Cray-HPE/container-images/pull/384
IS THIS A NEW FEATURE OR CRITICAL BUG FIX? bug fix
DOES THIS CHANGE INVOLVE ANY SCHEME CHANGES? N
REMINDER: HAVE YOU INCREMENTED VERSION NUMBERS? Y
REMINDER 2: HAVE YOU UPDATED THE COPYRIGHT PER hpe GUIDELINES: Copyright 2014-2021 Hewlett Packard Enterprise Development LP ? Y
Issues and Related PRs …
=> CASMPET-5237:update  node-exporter-smartmon image reference

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
Upgrade the golang version to fix the vulnarability issue.
To resolve this we are using the golang:1.17.3-alpine3.15 version for the grafterm.
https://github.com/Cray-HPE/container-images/pull/406 (merged)
https://github.com/Cray-HPE/cray-grafterm/pull/3 (merged)
* Resolves 
[CASMINST-4144](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4144)
* Change will also be needed in 
Need to create tag for 1.2 branch after merging this PR
* Future work required:
Bump the grafterm and sysmgmt-heatlh version in csm product repo.
* Documentation changes required
None
* Merge with/before/after
None
Done
gamora
Able to get the Grafterm graphs
None
=> CASMINST-4144: fix snyk issue by using the golang alpine 3.15 version

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/node_exporter-smartmon/daemonset.yaml
CASMMON-119: CPU THROTTLING - smartmon pods
Remove the cpu requests/limits for tsmartmon containers and rely on the defaults in the sysmgmt-health namespace
[CASMMON-119](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-119)
Slice
=> CASMMON-119:CPU THROTTLING - smartmon pods

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/istio/istio-alerts.yaml
The default istio alert rules have some unit errors (e.g., milliseconds vs seconds) and need adjustments in other cases. This PR will address false alarms caused by the default istio alert rules.
* Resolves [CASMPET-5374]
* `mug`
The istio alert rules were changed and verified on mug.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?
Low.
=> CASMPET-5374: adjust istio alert rules

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/istio/istio-performance-dashboard.json
CASMPET-5438: GRAFANA- Istio Performance Dashboard - Data not found
Fixed all the panels in Grafana Istio performance dashboard. Now all panels has data.
* Resolves: https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5438
hela
=> CASMPET-5438: GRAFANA- Istio Performance Dashboard - Data not found

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/switch/switch-alerts.yaml
CASMINST-5243:cray-sysmgmt-health chart failed due to duplicate alert name
Error: prometheusrules.monitoring.coreos.com "cray-sysmgmt-health-smartmon-alerts.rules" already exists chart=cray-sysmgmt-health command=ship namespace=sysmgmt-health version=0.25.0
https://jira-pro.its.hpecorp.net:8443/browse/CASM-3057
loftsman ship --charts-path . --manifest-path shs-cust.yaml
2022-08-17T13:59:59Z INF Initializing the connection to the Kubernetes cluster using KUBECONFIG (system default), and context (current-context) command=ship
2022-08-17T13:59:59Z INF Initializing helm client object command=ship
|\
| \
|  \
|___\      Shipping your Helm workloads with Loftsman
\--||___/
~~~~~~\_____/~~~~~~~
2022-08-17T13:59:59Z INF Ensuring that the loftsman namespace exists command=ship
2022-08-17T13:59:59Z …
=> CASMINST-5243:cray-sysmgmt-health chart failed 

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
[CASMMON-190](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-190) - Grafana piechart plugin issues in air-gapped systems
[CASMPET-4897](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-4897) - Grafana is missing the Vonage-status-panel plugin required by the Ceph - Cluster dashboard
Upgrading the pie-chart-panel plugin to the latest by creating a Grafana docker image with the build piechart plugin instead of downloading the piechart plugin while installing the chart. Grafana Upgrade and Dashboard improvements by supporting new visualizations. Setting the new path for plugins to download.
Resolves -
Adds pie chart panel to existing dashboards. Resolves the Grafana Ceph - Cluster dashboard reporting the following error - Panel plugin not found: Vonage-status-panel.
Tested on slice …
=> CASMMON-190/196 Path change for plugins

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/kyverno/kyverno.json, kubernetes/cray-sysmgmt-health/values.yaml
Monitor Kyverno policy metrics with Prometheus
As part of shasta monitoring, it may benefit you to have monitoring capabilities over both the state and execution of cluster-applied Kyverno policies. This includes monitoring over any applied changes to policies, any activity associated with incoming requests, and any results produced as an outcome. If enabled, monitoring will allow you to visualize and alert on applied policies, and is critical to overall cluster observability and compliance.
Kyverno exporter to get metrics from service monitor. Installation of the dashboard for the kyverno metrics through the .json file.
https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-236
* Mug successfully
=> CASMMON-236 - Grafana Dashboard for Kyverno

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/patch-node-exporter/patch-nodeexporter-alerts-job.yaml
Adding hook-delete-policy to delete the failed patch-nodeexporter-alerts job if it failed during installation.
This change is backward-compatible bugfix.
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5664
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5589
* `Slice`
- Was the upgrade tested? Yes.
=> CASMINST-5664 Prometheus error with web hook for node exporter

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/monitors/service-monitor.yaml, kubernetes/cray-sysmgmt-health/values.yaml
create promethisys service monitor for argo-workflows-workflow-controller service to scrape metrics.
https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-253
Tested on Frigg:
kubectl get ServiceMonitor -n sysmgmt-health  |grep argo
cray-sysmgmt-health-argo-only-argo-workflows-workflow-controlle   35m
lift of servicemonitors  after template change
ubectl get ServiceMonitor -n sysmgmt-health
NAME                                                              AGE
cray-dns-unbound-dns-unbound-exporter                             104d
cray-sysmgmt-health-argo-only-argo-workflows-workflow-controlle   35m
cray-sysmgmt-health-bos-etcd-exporter                             104d
cray-sysmgmt-health-bss-etcd-exporter                             104d
cray-sysmgmt-health-ceph-exporter …
=> CASMMON-253:servicemonitor for argo-workflows

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/unbounddns/unbound-dns.json
[CASMMON-254]  Rework sysmgmt-health Unbound Grafana dashboard to support new exporter
During the investigation of a customer issue, it was observed that the Prometheus metrics for Unbound DNS are missing.
The unbound-telemetry exporter is not working correctly and is now EOL and contains a security vulnerability that will not be patched now the project has been archived.
cray-dns-unbound now incorporates the letsencrypt unbound_exporter however the dashboard needs reworking to support it as some metrics are no longer available via this new exporter.
* Resolves [issue …
=> CASMMON-254 Rework sysmgmt-health Unbound Grafana dashboard to support new exporter

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/grok_exporter/goss-tests.json, kubernetes/cray-sysmgmt-health/dashboards_json/iuf/iuf-timing-dashboard.json, kubernetes/cray-sysmgmt-health/templates/grok-exporter/config-map.yaml
_Changes in grok exporter configuration as goss tests logs format is changed. We do not want to use scientific notation as the calculation is wrong on Grafana. Hence, when logging test duration is changed to seconds._
_Calculation of execution time for IUF product and IUF stage using the difference of maximum and minimum of operation end and operation start respectively instead of sum in IUF timing dashboard._
_Change is a backward compatible bugfix._
Resolves -
[CASM-3815](https://jira-pro.its.hpecorp.net:8443/browse/CASM-3815)
[CASM-3816](https://jira-pro.its.hpecorp.net:8443/browse/CASM-3816)
* `frigg`
_Changes tested and successfully verified._
- Install/upgrade-based …
=> CASM-3815 & CASM-3816 Grok-exporter config and IUF timing execution time changes; minor bug fixes

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-289
* Resolves- https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-289
hela
Events:
Type     Reason                  Age                From                     Message
----     ------                  ----               ----                     -------
Normal   Scheduled               15m                default-scheduler        Successfully assigned sysmgmt-health/prometheus-cray-sysmgmt-heal …
=> CASMMON-289: Prometheus image not present

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/kafka/kafka.json, kubernetes/cray-sysmgmt-health/dashboards_json/kafka/zookeeper.json, kubernetes/cray-sysmgmt-health/templates/prometheus/monitors/strimzi-pod-monitor.yaml
Need patched version of SMA-1.7 that allows Nersc to install HPE-built software and keep their scalability settings. 
e.g. rsyslog-aggregator config file needs to persist, a number of instances of rsyslog-aggregator, kafka, elasticsearch need to persist, and es-curator needs to create indexes with the configured number of shards. The Kafka partition count needs to persist. 
[CASMSMF-7353](https://jira-pro.its.hpecorp.net:8443/browse/CASMSMF-7353)
* Resolves [CASMMON-296](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-296) and [CASMMON-295](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-295)
* `<wasp>`
Tested successfully.
- Was the upgrade tested? Yes.
=> CASMMON-295 Monitor the SMF Kafka server and zookeeper

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/grok-exporter/deployment.yaml
_Grok-exporter is not running on ncn-m001 as it comes up last when nodes are installed on pit. The other master nodes of m002 or m003 is taking ownership of the m001 instance before it is up._
_This fix will resolve the issue and wait for m001 to take the ownership of the pod._
* Resolves [CASMMON-299](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-299)
* `<mug>`
* `<hela>`
_Tested and success verified._
ncn-m001:/mnt/developer/sum # kubectl get all -n sysmgmt-health | grep grok
pod/cray-sysmgmt-health-grok-exporter-6b64849ff5-2cc8z              1/1     Running            0          3m34s
pod/cray-sysmgmt-health-grok-exporter-6b64849ff5-htsps              1/1     Running            0          3m35s …
=> CASMMON-299 Grok-exporter issue with running on ncn-m001 Release/1.4

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
cray-sysmgmt-health fails to install on k8s 1.22
Issues and Related PRs
[CASMTRIAGE-5496](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5496)
Implementation of the upgraded jettech/kube-webhook-certgen image from 1.2.1 to 1.3.0
Tested on Starlord system.
All images and chart gets deployed without issues -
```
ncn-m001:/mnt/developer/sum # kubectl get all -n sysmgmt-health
NAME                                                                READY   STATUS      RESTARTS   AGE
pod/alertmanager-cray-sysmgmt-health-kube-p-alertmanager-0          2/2     Running     1          53m
pod/cray-sysmgmt-health-canu-test-7b5fc744dd-jbjgf                  2/2     Running     0          13s
pod/cray-sysmgmt-health-grafana-768766bb95-qp87c                    3/3     Running     0 …
```
=> CASMTRIAGE-5496 cray-sysmgmt-health fails to install on k8s 1.22

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/thanos/thanos-compactor.json, kubernetes/cray-sysmgmt-health/dashboards_json/thanos/thanos-overview.json, kubernetes/cray-sysmgmt-health/dashboards_json/thanos/thanos-query.json, kubernetes/cray-sysmgmt-health/dashboards_json/thanos/thanos-ruler.json, kubernetes/cray-sysmgmt-health/dashboards_json/thanos/thanos-sidecar.json, kubernetes/cray-sysmgmt-health/templates/_helpers.tpl, kubernetes/cray-sysmgmt-health/templates/thanos/alertmanager/secret.yaml, kubernetes/cray-sysmgmt-health/templates/thanos/compactor/compactor-deployment.yaml, kubernetes/cray-sysmgmt-health/templates/thanos/compactor/compactor-service-monitor.yaml, kubernetes/cray-sysmgmt-health/templates/thanos/compactor/compactor-service.yaml, kubernetes/cray-sysmgmt-health/templates/thanos/ingress.yaml, kubernetes/cray-sysmgmt-health/templates/thanos/querier/querier-deployment.yaml, kubernetes/cray-sysmgmt-health/templates/thanos/querier/querier-service-monitor.yaml, kubernetes/cray-sysmgmt-health/templates/thanos/querier/querier-service.yaml, kubernetes/cray-sysmgmt-health/templates/thanos/rbac-thanos.yaml, kubernetes/cray-sysmgmt-health/templates/thanos/store/store-deployment.yaml, kubernetes/cray-sysmgmt-health/templates/thanos/store/store-service.yaml, kubernetes/cray-sysmgmt-health/templates/thanos/upload-secret.yaml, kubernetes/cray-sysmgmt-health/values.yaml
This PR includes prometheus scalability and high availability with thanos.  It  has several components such as Querier, Compactor, StoreAPI, Ruler, etc.
* Resolves - https://jira-pro.it.hpe.com:8443/browse/CASM-3496
Gamora
Mug
Starlord
ncn-m001:~ # kubectl get pods -n sysmgmt-health | grep prom-
prometheus-cray-sysmgmt-health-kube-p-prom-0                    3/3     Running             0          2d23h
prometheus-cray-sysmgmt-health-kube-p-prom-1 …
=> CASM-3496: Highly available Prometheus setup with long term storage with Thanos

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
cray-sysmgmt-health fails to install on k8s 1.22 using jettech/kube-webhook-certgen:v1.3.0 as well.
This PR uses the registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.3.0 to fix it.
Issues and Related PRs
[CASMMON-322](https://jira-pro.it.hpe.com:8443/browse/CASMMON-322)
Implementation of the registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.3.0 image.
Tested on vShasta Ashton system.
All images and chart gets deployed without issues -
```
Type    Reason          Age   From               Message
----    ------          ----  ----               -------
Normal  Scheduled       65s   default-scheduler  Successfully assigned sysmgmt-health/cray-sysmgmt-health-kube-p-admission-patch-qjkcb to ncn-w003
Normal  AddedInterface  65s   multus             Add eth0 …
```
=> CASMMON-322 jettech/kube-webhook-certgen:v1.3.0 doesn't work with k8s 1.22

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
cray-sysmgmt-health fails to install on k8s 1.22 using jettech/kube-webhook-certgen:v1.3.0 as well.
This PR uses the registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.3.0 to fix it.
Issues and Related PRs
[CASMMON-322](https://jira-pro.it.hpe.com:8443/browse/CASMMON-322)
Implementation of the registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.3.0 image.
Tested on vShasta Ashton system.
All images and chart gets deployed without issues -
```
Type    Reason          Age   From               Message
----    ------          ----  ----               -------
Normal  Scheduled       65s   default-scheduler  Successfully assigned sysmgmt-health/cray-sysmgmt-health-kube-p-admission-patch-qjkcb to ncn-w003
Normal  AddedInterface  65s   multus             Add eth0 …
```
=> CASMMON-322 jettech/kube-webhook-certgen:v1.3.0 doesn't work with k8s 1.22 - main

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/grok-exporter/deployment.yaml
cray-sysmgmt-health grok-exporter node affinity is wrong for mercury. It is using ncn-m001, ncn-m002 and ncn-m003 by default. But mercury has no NCNs and it will fail.
_This change is a backward-compatible bugfix_
* Resolves [CASMPET-6651](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6651)
* Change will also be needed in `<release/1.4>`
* `<frigg>`
* Virtual Shasta - Ashton
* Mercury
_The changes tested and success verified._
```
sysmgmt-health   cray-sysmgmt-health-grok-exporter-6dfd6c455b-9r7xn                1/1     Running                      0              3m20s   10.32.128.5     k8s-master-sigma7-3    <none>           <none>
sysmgmt-health   cray-sysmgmt-health-grok-exporter-6dfd6c455b-grbq6                1/1     Running                      0 …
```
=> CASMPET-6651 cray-sysmgmt-health node affinity is wrong for mercury

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/thanos/upload-secret.yaml
https://jira-pro.it.hpe.com:8443/browse/CASMMON-327
* Resolves - https://jira-pro.it.hpe.com:8443/browse/CASMMON-327
* Virtual Shasta - Fearne
pit:~ # kubectl get pods -n sysmgmt-health
NAME                                                            READY   STATUS      RESTARTS     AGE
alertmanager-cray-sysmgmt-health-kube-p-alertmanager-0          2/2     Running     1 (8h ago)   8h
cray-sysmgmt-health-canu-test-6688766dd9-672nt                  2/2     Running     0            8h
cray-sysmgmt-health-grafana-768766bb95-8xm7x                    3/3 …
=> CASMMON-327: cray-symgmt-health can fail on new installs

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/kafka/kafka-connect.json, kubernetes/cray-sysmgmt-health/dashboards_json/kafka/kafka.json, kubernetes/cray-sysmgmt-health/dashboards_json/kafka/zookeeper.json
_Dashboard for kafka-connect after implementation of the jmx-exporter in [CASMMON-330](https://jira-pro.it.hpe.com:8443/browse/CASMMON-330)._
* Resolves [CASMMON-331](https://jira-pro.it.hpe.com:8443/browse/CASMMON-331)
* Merge after `<https://github.hpe.com/hpe/hpc-car-sma-kafka-connect/pull/17>`
* `<mug>`
* `<hela>`
_The changes tested and success verified._
https://grafana.cmn.mug.hpc.amslabs.hpecorp.net/d/connect/kafka-connect?orgId=1&refresh=10s
```
ncn-m001:/mnt/developer/sum # helm upgrade -n sma cp-kafka-connect cp-kafka-connect-1.4.0.tgz
Release "cp-kafka-connect" has been upgraded. Happy Helming!
NAME: cp-kafka-connect
LAST DEPLOYED: Thu Jul  6 05:32:58 2023
NAMESPACE: sma
STATUS: deployed
REVISION: 26
TEST SUITE: None
NOTES:
This chart installs a …
```
=> CASMMON-331 Add kafka-connect dashboard in cray-sysmgmt-health

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
_Impacted NCN-{M,W} console logs as they are filled with AppArmor errors. Critical bug fix._
_Backwards compatible bugfix._
* Resolves [CASMMON-334](https://jira-pro.it.hpe.com:8443/browse/CASMMON-334)
* [CAST-33453](https://jira-pro.it.hpe.com:8443/browse/CAST-33453)
* Change will also be needed in `<release1.4>`
* `<hela>`
_Tested successfully and no dmesg errors were seen or audit logs created after the changes._
- Upgrade tested.
Latest chart from PR -
```
ncn-m001:/mnt/developer/sum # helm list -A | grep cray-sys
cray-sysmgmt-health                     sysmgmt-health          1               2023-07-31 10:02:00.643470856 …
```
=> CASMMON-334 Stop the flood of useless Apparmor messages for node-exporter pod - release/1.4

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
_Impacted NCN-{M,W} console logs as they are filled with AppArmor errors. Critical bug fix._
_Backwards compatible bugfix._
* Resolves [CASMMON-334](https://jira-pro.it.hpe.com:8443/browse/CASMMON-334)
* [CAST-33453](https://jira-pro.it.hpe.com:8443/browse/CAST-33453)
* Change will also be needed in `<release1.4>`
* `<mug>`
_Tested successfully and no dmesg errors were seen or audit logs created after the changes._
- Upgrade tested.
Latest chart from PR -
```
ncn-m001:/mnt/developer/sum # helm list -A | grep cray-sys
cray-sysmgmt-health                     sysmgmt-health  1               2023-07-31 10:00:54.455706616 +0000 UTC …
```
=> CASMMON-334 Stop the flood of useless Apparmor messages for node-exporter pod - master

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/uan/nodeExporter/endpoints.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/uan/nodeExporter/service.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/uan/nodeExporter/servicemonitor.yaml, kubernetes/cray-sysmgmt-health/values.yaml
create endpoint,service and service monitor to enabling SMART data on UAN
[
_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._](
https://jira-pro.it.hpe.com:8443/browse/CASMMON-340
tested on shandy
custmization.yaml changes under cray-sysmgmt-health chart
uanNodeExporter:
enabled: true
endpoints:
- 10.252.1.23
ncn-m001:/mnt/developer/ram # curl http://10.252.1.23:9100/metrics |more
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0# HELP node_exporter_build_info A metric with a constant '1' value labeled by version, revision, branch, and goversion from which node_exporter was …
=> create endpoint,service and service monitor to enabling UAN SMART data

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
Fix thanos-ruler-kube-prometheus-stack-thanos-ruler pod disruption budget.
This regarding the pod disruption budget for thanos-ruler-kube-prometheus-stack-thanos-ruler .    We see that this statefulset is defined as a singleton but the pod disruption budget doesn't allow that singleton pod to be removed when a node is drained.    Kubernetes guidelines say that singleton pods should tolerate downtime and not have a pod disruption budget. 
[CASMMON-342](https://jira-pro.it.hpe.com:8443/browse/CASMMON-342)
before the fix
kubectl -n sysmgmt-health get pdb
NAME                                 MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
kube-prometheus-stack-thanos-ruler   1               N/A               0 …
=> Fix thanos-ruler-kube-prometheus-stack-thanos-ruler pod disruption budget

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/timescaledb/timescaledb.json
CASMMON-344: create time scale grafana dashboard
* Resolves: https://jira-pro.it.hpe.com:8443/browse/CASMMON-344
hela
=> Casmmon 344: add timescale grafana dashboard(release/1.4)

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/timescaledb/timescaledb.json
CASMMON-344: create time scale grafana dashboard
* Resolves :  https://jira-pro.it.hpe.com:8443/browse/CASMMON-344
=> CASM-4539:add timescale grafana dashboard

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/smartmon/smartmon.json, kubernetes/cray-sysmgmt-health/dashboards_json/timescaledb/timescaledb.json
CASMMON-345: CSM 1.5: Grafana dashboard for smartmon , instances name is not listing instead ip is listing
CASMMON-346: CSM 1.5: Grafan TimescaleDB dashboard ALL option is not available for list of postgres pods
CASMMON-347: CSM 1.5: Grafan TimescaleDB dashboard variable name is mentioned as cluster instead of pod
* Resolves: 
* CASMMON-345: https://jira-pro.it.hpe.com:8443/browse/CASMMON-345
* CASMMON-346: …
=> CASMMON-345-and-346(release 1.5 and 1.6)

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
* Resolves - https://jira-pro.it.hpe.com:8443/browse/CASMMON-369
Slice
```
ncn-m001:/mnt/admin/dmb/ceph # ceph df
--- RAW STORAGE ---
CLASS    SIZE   AVAIL    USED  RAW USED  %RAW USED
ssd    31 TiB  21 TiB  10 TiB    10 TiB      33.01
TOTAL  31 TiB  21 TiB  10 TiB    10 TiB      33.01
--- POOLS ---
POOL                        ID  PGS   STORED  OBJECTS     USED  %USED  MAX AVAIL
.mgr …
```
=> New Thanos Service is configured without storage limits

.github/workflows/charts-lint-test-scan.yml, kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
* Resolves - https://jira-pro.it.hpe.com:8443/browse/CASMMON-364
Odin (CSM-1.5)
ClusterStor E1000 - kjlmo900.hpc.amslabs.hpecorp.net
```
ncn-w003:/var/lib/node_exporter # ls
fetch_health.sh  redfish-smart-1.prom  redfish-smart-2.prom  smartmon.prom
ncn-w003:/var/lib/node_exporter # cat redfish-smart-2.prom
#HELP redfish_up Redfish Server Monitoring availability
#TYPE redfish_up gauge
redfish_up{host="kjlmo900.hpc.amslabs.hpecorp.net",redfish_instance="10.21 …
```
=> Retrieve SMART metrics from E1000 via redfish and send via Prometheus

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/redfish-exporter/configmap.yaml
* Resolves - https://jira-pro.it.hpe.com:8443/browse/CASMMON-396
Odin
After including the configmap, pods are healthy.
```
ncn-m001:~ # kubectl get pods -n sysmgmt-health | grep redf
cray-sysmgmt-health-redfish-cron-28612080-g72pf                 0/1     Completed   0               17h
cray-sysmgmt-health-redfish-cron-28612440-v47vv                 0/1     Completed   0               11h …
```
=> CASMMON-396

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/grok-exporter/deployment.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/node_exporter-smartmon/daemonset.yaml, kubernetes/cray-sysmgmt-health/values.yaml
Update sysmgmt-health with "node-role.kubernetes.io/control-plane" changes for k8s 1.24. Additionally, have charts use docker image docker-kubectl version 1.24.17 for k8s 1.24. This is a necessary change for CSM 1.6.
* Resolves [CASMPET-7085](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7085)
Upgraded chart on Beau to this chart. Everything upgraded successfully.
Low risk
=> CASMPET-7085 update chart with node-role.kubernetes.io/control-plane changes for k8s 1.24

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/_helpers.tpl, kubernetes/cray-sysmgmt-health/values.yaml
Resolved CSM build failure due to few image issues.
* Resolves - https://jira-pro.it.hpe.com:8443/browse/CASMMON-401
Fanta
```
ncn-m001:/mnt/developer/shreni # kubectl get pods -n sysmgmt-health
NAME                                                             READY   STATUS    RESTARTS   AGE
cray-sysmgmt-health-canu-test-7c7468b479-t78lg                   2/2     Running   0          6m38s …
```
=> CSM build issue fix

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/monitors/metallb-controller.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/monitors/metallb-speaker.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/monitors/metallb.yaml, kubernetes/cray-sysmgmt-health/values.yaml
Conversion to victoria-metrics broke spire chart upgrade.
these VMScrape and other VM specific CRDs should be consolidated into a single chart rather than scattered liberally across unbound, kea, metallb, spire etc. So moving to cray-sysmgmt-health chart
[_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._
* Merge with/before/after `<insert PR URL here>`](https://jira-pro.it.hpe.com:8443/browse/CASMMON-415)
=> CASMMON-415 Conversion to victoria-metrics broke spire chart upgrade

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/iscsi/iscsi_daemon.yaml, kubernetes/cray-sysmgmt-health/values.yaml
This is  in the context of iSCSI based boot content projection feature. This has the daemonset pod to export iscsi metrics to node exporter / prometheus. 
CASMPET-6793
Tested on Odin.
=> CASMPET-6820 daemonset pod to export iscsi metrics

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
Version of iscsi_metrics image and cray-sysmgt-health chart were not appropriate due to which the Jenkins build failed. 
Corrected the versions. 
CASMPET-6820
Mug
None.
_Are there known issues with these changes? Any other special considerations?_
None.
=> Fixed the versions of iscsi_metrics image and cray-sysmgmt-health chart

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/node_exporter_webconfig/web.yml, kubernetes/cray-sysmgmt-health/templates/node-exporter/configmap.yaml, kubernetes/cray-sysmgmt-health/values.yaml
node_exporter to authenticate itself with its TLS certificate
Fix CVE's in artifactory.algol60.net/csm-docker/stable/gcr.io/google_containers/hyperkube:v1.18.0
system monitoring and metrics collection, ensuring the security of data transmission is paramount. This article delves into the configuration of Transport Layer Security (TLS) and HTTPS for the Prometheus Node Exporter, alongside implementing basic authentication. These measures are critical for safeguarding the integrity and confidentiality of the data as it moves between the Node Exporter and Prometheus server, offering an essential layer of security against potential eavesdropping or unauthorized access. …
=> CASMMON-413 and CASMMON-424  node_exporter to authenticate itself with its TLS certificate

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/iscsi/iscsi_daemon.yaml
The iSCSI metrics related pods in bad state as iSCSI was not configured/provisioned. This issue is addressed by preventing these pods from scheduling on nodes which do not have iSCSI labels.
This is in the context of CASM-3756 where iSCSI metrics were added via CASMPET-6820. So there are daemonset pods to collect iscsi metrics on each of the worker node where iscsi is configured and Marshal agent is running. But testing on freshly installed CSM 1.6 system these pods failed as iSCSI was not configured. This iscsi will be configured via ansible playbooks. 
But these have to be run manually. This is getting automated which is in progress. 
The other approach to address this issue by preventing these iscsi pods from scheduling on nodes which are not configured with iscsi. So currently this is …
=> CASMTRIAGE-7207: CT ITF triage kubectld pods unhealthy

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/kubernetes/persistentvolumesusage.json, kubernetes/cray-sysmgmt-health/templates/prometheus/monitors/patch-service-monitors-job.yaml, kubernetes/cray-sysmgmt-health/values.yaml
VM not dropping metrics with morethan 40 lebels
kubectl logs -n sysmgmt-health vminsert-vms-68d95cdfc7-92tmg
2024-09-11T03:29:17.607Z        info …
=> CASMMON-432 & CASMTRIAGE-7282 fix set metricsBindAddress and VMINSERT drop metrics more lebels

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/iscsi/iscsi_daemon.yaml
This issue is caused due to hostpath /etc/target/saveconfig.json not existed when iscsi_daemon.yaml was deployed. Mounting '/etc/target/' directory instead of '/etc/target/saveconfig.json' fixed the issue.
None.
* Resolves [issue id](issue link): CASMPET-7238
* Change will also be needed in `<insert branch name here>`: N/A
* Future work required by [issue id](issue link): N/A 
* Documentation changes required in [issue id](issue link): N/A 
* Merge with/before/after `<insert PR URL here>`: N/A
Tested on both Starlord and Fanta having CSM 1.6.0-alpha.67 installed. 
Starlord and Fanta
Reproduced the issue when iSCSI was not configured. /etc/target/saveconfig.json directory got created on host as this file was not existed (iSCSI was not configured). When iSCSI was configured via CFS ansible …
=> CASMPET-7238:/etc/target/saveconfig.json exists as a dir instead of file

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
Upgraded VM from to resolve vulnerability
https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack
Victoria metrics components:
Vmselect
Vmagent
Vmalert
Vmstorage
[
* Merge with/before/after `<insert PR URL here>`](https://jira-pro.it.hpe.com:8443/browse/CASMMON-458)
uninstall script logs
helm uninstall -n sysmgmt-health cray-sysmgmt-health --debug
uninstall.go:102: [debug] uninstall: …
=> CASMMON-458 Victoriametrics Upgrate

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
grafana and node exporter image issues for Victoria metrics 0.24.5
https://jira-pro.it.hpe.com:8443/browse/CASMMON-458
helm template cray-sysmgmt-health | grep image: | grep "/artifactory"
=> grafana and node exporter image issues for Victoria metrics 0.24.5

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
Couple of iSCSI SBPS metrics  values are not correct due to old image of iscsi-metrics where this issue has been fixed in 1.0.1 of iscsi-metrics image. Updating 'cray-sysmgtmt-health' chart to use 1.0.1 of iscsi-metrics image and update the chart version.
CASMTRIAGE-7285
* Resolves [issue id](issue link): CASMTRIAGE-7490:
Testing was done on fanta as part of CASMTRIAGE-7285. 
iscsi-metrics image with 1.0.1 version was downloaded manually onto the system and tested. 
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?: yes
- Were continuous integration tests run? If not, why?: N/A
- Was upgrade tested? If not, why?: N/A 
- Was downgrade tested? If not, why?: N/A
- Were new tests (or test issues/Jiras) created for this change?: No
None
- [NA] …
=> CASMTRIAGE-7490: Couple of Iscsi metrics values are not correct

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
Observed several thousand restarts of cray-sysmgmt-health-redfish-exporter on fanta
[
](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7567)
* `<development system>`
ncn-m001:~/ram/test # kubectl get pods -n sysmgmt-health |grep redfish
cray-sysmgmt-health-redfish-exporter-8557cfff74-64v5h           1/1     Running …
=> CASMTRIAGE-7567

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
This is to use the iscsi-metrics image which is having the fix for CASMPET-7410 and also bump up the cray-sysmgt-health chart version
None
* Resolves [issue id](issue link): CASMPET-7410
* Change will also be needed in `<insert branch name here>`: N/A 
* Future work required by [issue id](issue link): N/A
* Documentation changes required in [issue id](issue link): N/A
* Merge with/before/after `<insert PR URL here>`: N/A
Fix for CASMPET-7410 has been tested on tyr which had 1.6.1 rc-7. One more round of testing will be done once this fix is merged and the bits having this fix gets installed. 
N/A
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?N/A
- Were continuous integration tests run? If not, why?: N/A 
- Was upgrade tested? If not, …
=> Casmpet 7410 update image

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/logstash/logstash.json, kubernetes/cray-sysmgmt-health/values.yaml
create grok exporter docker image for cray-sysmgmt-health
* Related to https://jira-pro.it.hpe.com:8443/browse/CASMMON-511
* wasp
=> CASMMON-511 create grok exporter docker image for cray-sysmgmt-health

kubernetes/cray-sysmgmt-health/Chart.yaml
This PR is to bump up the version of chart to 1.2.5 that was missed in the previous merge from this branch.
=> bump up chart version to 1.2.5

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/alertmanager/alertmanager.yaml, kubernetes/cray-sysmgmt-health/values.yaml
Victoriametrics upgrade from 0.25.0 to 0.42.0
upgrade node exporter
https://jira-pro.it.hpe.com:8443/browse/CASMMON-481
https://jira-pro.it.hpe.com:8443/browse/CASMMON-482
Installtion logs
loftsman ship --manifest-path ./shs-cust.yaml --charts-path .
2025-04-17T07:16:13Z INF Initializing the connection to the Kubernetes cluster using KUBECONFIG (system default), and context (current-context) command=ship
2025-04-17T07:16:13Z INF Initializing helm client object command=ship
|\
| \
|  \
|___\      Shipping your Helm workloads with Loftsman
\--||___/
~~~~~~\_____/~~~~~~~
2025-04-17T07:16:13Z INF Ensuring that the loftsman namespace exists command=ship
2025-04-17T07:16:13Z INF Loftsman will use the packaged charts at . as the Helm …
=> CASMMON-508 VM upgrade 0.42.0

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
Fix for CASMPET-7410 had prometheus formatting errors, which are fixed in iscsi-metrics . The cray-sysmgt-health chart version needs to be updated as the latest iscsi-metrics image has to be pulled.  So this PR is to pull the iscsi-metrics image having the fix and bump up the cray-sysmgt-health chart version.
CASMPET-7410
https://github.com/Cray-HPE/iscsi-metrics/pull/6
https://github.com/Cray-HPE/iscsi-metrics/pull/5
https://github.com/Cray-HPE/cray-sysmgmt-health/pull/197
* Resolves [issue id](issue link): CASMPET-7410
* Change will also be needed in `<insert branch name here>`: N/A 
* Future work required by [issue id](issue link): N/A 
* Documentation changes required in …
=> Fixing the prometheus formatting issue

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
The pod logs and the Victoria metrics GUI started reporting some errors after upgrading Victoria-metrics-k8s-stack. This PR fixes all the minor bugs reported as a part this upgrade.
* Resolves https://jira-pro.it.hpe.com:8443/browse/CASMMON-532
* starlord
```
ncn-m001:~ # kubectl logs -n sysmgmt-health cray-sysmgmt-health-victoria-metrics-operator-dc544f8bc-8x2gn  | grep error
ncn-m001:~ # kubectl logs -n sysmgmt-health vmalertmanager-vms-0 | grep ERROR
Defaulted container "alertmanager" out of: alertmanager, config-reloader
ncn-m001:~ # 
```
=> CASMMON-532 Fix all the minor bugs reported as a part of Victoria-metrics-k8s-stack upgrade

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
This PR is to upgrade the bitnami/kubectl image to the latest version 1.33.1
* Resolves https://jira-pro.it.hpe.com:8443/browse/CASMMON-543
* Makes the changes missed in  https://jira-pro.it.hpe.com:8443/browse/CASMSMF-8515 
* wasp
- This image is used when the chart is uninstalled. It clears up all the vm crds in the namespace. So for testing we can check If the crds have been cleared when the chart gets uninstalled. 
- The cilium Hubble pod scrape remains because it was not created as a part of the cray-sysmgmt-health chart.
```
ncn-m001:/mnt/developer/akshar/543-CASMMON # helm uninstall -n sysmgmt-health cray-sysmgmt-health 
release "cray-sysmgmt-health" uninstalled
ncn-m001:/mnt/developer/akshar/543-CASMMON # echo $vm_crds …
```
=> CASMMON-543 upgrade bitnami/kubectl image to 1.33.1

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/cilium/cilium-agent-metrics.json, kubernetes/cray-sysmgmt-health/dashboards_json/cilium/cilium-hubble-metrics.json, kubernetes/cray-sysmgmt-health/dashboards_json/cilium/cilium-policy-verdicts.json, kubernetes/cray-sysmgmt-health/templates/grafana/configmap.yaml, kubernetes/cray-sysmgmt-health/values.yaml
Cilium and Hubble expose metrics which can be visualised in Grafana. This PR configures the required scrapes and the dashboards for visualisation.
* Resolves https://jira-pro.it.hpe.com:8443/browse/CASMNET-2189
* starlord
Cilium Hubble Metrics
=> CASMNET-2189 Add Cilium dashboards to Grafana
