Cray-HPE/cray-sysmgmt-health

kubernetes/cray-sysmgmt-health/Chart.yaml
=> bump version chart version

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/disk-space/disk-space.yaml
cray-sysmgmt-health : https://connect.us.cray.com/jira/browse/CASMMON-76
NOTE FOR RELEASE BRANCHES: YOU NO LONGER NEED TO UPDATE THE .version VERSION ON EVERY PR IF THE PR DOES NOT CHANGE THE CONTENTS OF THE GENERATED CONTAINER IMAGE. IF YOU DO UPDATE .version, YOU ALSO NEED TO UPDATE THE Chart.yaml VERSION (if …
=> CASMMON-76:monitoring for space on root file system

.github/workflows/charts-lint-test-scan-cron.yml, .github/workflows/charts-lint-test-scan.yml, kubernetes/.snyk, kubernetes/cray-sysmgmt-health/.gitignore, kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/requirements.lock, kubernetes/cray-sysmgmt-health/requirements.yaml, kubernetes/cray-sysmgmt-health/templates/grafterm/deployment.yaml, kubernetes/cray-sysmgmt-health/templates/node-exporter/post-install.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/monitors/patch-service-monitors-job.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/node_exporter-smartmon/daemonset.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/patch-node-exporter/patch-nodeexporter-alerts-job.yaml, kubernetes/cray-sysmgmt-health/values.yaml
Followed the objectives in CASM-2670 [0].
All of the images being used are now from algol60 artifactory. The
one exception is smartmon which is now using the community image. The
image built from container-images had a new vulnerability and a
rebuild didn't fix the problem. That image is no longer built by
container-images after some investigation of how it was being built
and we'll use the community image rather than rebuild it.
The community smartmon image also has the vulnerability but there's
no fix for it yet. I tried to configure snyk to ignore the
vulnerability but that's not working for some reason. This is why
scan-images is set to `false` in the workflows. A JIRA will be opened
to investigate why ignoring vulnerabilities isn't working.
scan-charts is set to `false` in the …
=> CASMPET-5038: Update image refs in charts

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/patch-node-exporter/configmap.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/patch-node-exporter/patch-nodeexporter-alerts-job.yaml
Prometheus monitor filter
cray-sysmgmt-health : https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-94
NOTE FOR RELEASE BRANCHES: YOU NO LONGER NEED TO UPDATE THE .version VERSION ON EVERY PR IF THE PR DOES NOT CHANGE THE CONTENTS OF THE GENERATED CONTAINER IMAGE. IF YOU DO UPDATE .version, YOU ALSO NEED TO UPDATE THE Chart.yaml VERSION (if you have one). IF YOU ARE ONLY …
=> CASMMON-94: prometheus rule node:node_num_cpu:sum missing variables

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
Updates prometheus operator ghostunnel image based on recently created container-images for ghostunnel v1.6.0
* Resolves [CASMPET-5224](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5224)
* Change will also be needed in NA
* Future work required by NA
* Documentation changes required NA
* Merge with/before/after NA
vshasta
```
C02YP47BLVCG:my_workspace kim.jensen$ kubectl get pods -A | grep promet-oper
sysmgmt-health      cray-sysmgmt-health-promet-operator-7df8c5bc49-rjhmt              2/2     Running            0          4m38s
C02YP47BLVCG:my_workspace kim.jensen$ kubectl describe pod cray-sysmgmt-health-promet-operator-7df8c5bc49-rjhmt -n sysmgmt-health | grep "Image:" | grep ghost
Image:         gcr.io/vsha-kjensen-35682334251699053/ghostunnel/ghostunnel:v1.6.0 …
```
=> CASMPET-5224 main : SECURITY : update ghostunnel for sec vulnerabilities

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/istio/istio-alerts.yaml
cray-sysmgmt-health : istio alerts
NOTE FOR RELEASE BRANCHES: YOU NO LONGER NEED TO UPDATE THE .version VERSION ON EVERY PR IF THE PR DOES NOT CHANGE THE CONTENTS OF THE GENERATED CONTAINER IMAGE. IF YOU DO UPDATE .version, YOU ALSO NEED TO UPDATE THE Chart.yaml VERSION (if you have one). IF YOU ARE ONLY …
=> CASMPET-5098 : istio alerts

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/grafana/dashboards/ceph-nautilus/radosgw-detail.yaml, kubernetes/cray-sysmgmt-health/templates/grafana/dashboards/ceph-nautilus/radosgw-overview.yaml, kubernetes/cray-sysmgmt-health/templates/grafana/dashboards/ceph-nautilus/rbd-overview.yaml
fixing ceph grafana dashbord timing issues.
Resolves  [CASMPET-5387][CASMPET-5386][CASMPET-5385]
slice
=> Casmpet 5387

kubernetes/cray-sysmgmt-health/Chart.yaml
Prometheus upgrade as requested by NERSC to latest version of Prometheus due to issues with remote write functionality. In fact, version 2.14.0 was released yesterday and includes 3 bug fixes for remote write, and it looks like most releases since 2.8 (what we're currently using) also include fixes. 
[CASMMON-157](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-157)
verified the logs 
kubectl logs -n sysmgmt-health      prometheus-cray-sysmgmt-health-promet-prometheus-0  prometheus
ts=2022-06-21T10:06:52.755Z caller=main.go:535 level=info msg="Starting Prometheus Server" mode=server version="(version=2.36.1, branch=HEAD, revision=3c0a100dec2950f23e91f7efbf8867750960807d)"
ts=2022-06-21T10:06:52.756Z caller=main.go:540 …
=> CASMMON-157: updating latest version of Promethesys

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/hwmon/hwmon-temperature.json
CASMMON-159: Investigate temperature hardware monitoring dashborads for NCNS in SHS
* Resolves - https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-159
slice
=> CASMMON-159: Investigate temperature hardware monitoring dashborads for NCNS in SHS

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/prometheus-network-exporter.json
CASMMON-187:Prometheus Network Exporter dashboard issue
slice and mug
=> CASMMON-187:Prometheus Network Exporter dashbord issue

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/snmp/snmpstats.json
CASMMON-189: support multiple switches for snmp stats dashboard
slice and mug
=> CASMMON-189: support multiple switches for snmp stats dashboard

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/switch/switch-alerts.yaml, kubernetes/cray-sysmgmt-health/values.yaml
CASMMON-188 create snmp prometheus alerts
[CASMMON-188](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-188)
Test logs
=> Casmmon 188

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
CASMMON-196
Upgrade grafana to 8.x for pie chart panel in the existing dashboards.
Grafana Upgrade and Dashboard improvements by supporting new visualizations.
=> CASMMON-196

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/disk-space/disk-space.yaml
CASM-3398: Need Thresholds for CPU and Memory Alerts for NCNs
* Resolves : https://jira-pro.its.hpecorp.net:8443/browse/CASM-3398
Mug
=> CASM-3398: Need Alerts for CPU and Memory usage for NCNs

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/disk-space/disk-space.yaml
Prometheus alerts expression fix for POD CPU usage.
Resolves [CASMTRIAGE-4770](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4770)
* `mug`
Changes tested and successfully verified.
=> CASMTRIAGE-4770: Prometheus alerts expression fix for POD CPU usage

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
Prometheus updated to the current stable version v2.41.0, alert manager to v0.25.0, and node-exporter to v1.5.0.
Backward compatible.
* Resolves - [CASMMON-244](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-244)
* `mug` successfully
Snips of the testing -
How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?
- Upgrade was tested.
prometheus_build_info{branch="HEAD", endpoint="web", goarch="amd64", goos="linux", goversion="go1.19.4", instance="10.44.0.2:9090", job="cray-sysmgmt-health-promet-prometheus", namespace="sysmgmt-health", pod="prometheus-cray-sysmgmt-health-promet-prometheus-0", revision="c0d8a56c69014279464c0e15d8bfb0e153af0dab", service="cray-sysmgmt-health-promet-prometheus" …
=> CASMMON-244: Update Prometheus to current stable release version v2.41.0

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/grok-exporter/goss-tests.json, kubernetes/cray-sysmgmt-health/templates/grok-exporter/config-map.yaml, kubernetes/cray-sysmgmt-health/templates/grok-exporter/deployment.yaml, kubernetes/cray-sysmgmt-health/templates/grok-exporter/service.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/monitors/service-monitor.yaml, kubernetes/cray-sysmgmt-health/values.yaml
New feature - Grok exporter deployment, service, service monitor & Grafana dashboard for Goss tests.
[CASMMON-255](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-255)
[CASMMON-241](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-241)
* `mug` and `frigg`
- Validation checks and goss tests ran for verification of metrics and dashboard.
=> CASMMON-255: Create grok exporter deployment, service, service monitor & Grafana dashboard for Goss tests.

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/disk-space/disk-space.yaml
Opensearch PVC monitoring alerts:
85% warning
90% critical
* Resolves - [https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-228](url)
Gamora
=> CASMMON-228: OpenSearch PVC monitorining alert

kubernetes/cray-sysmgmt-health/Chart.yaml
1.5.0-alpha.21 prometheus-cray-sysmgmt-health-kube-p-prometheus-0 in IPBO
* Resolves- https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5137
=> CASMTRIAGE-5137

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/alertmanager/ingress.yaml, kubernetes/cray-sysmgmt-health/templates/grafana/ingress.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/ingress.yaml, kubernetes/cray-sysmgmt-health/values.yaml
* Resolves [CASMPET-6514](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6514)
* mug
* dorian
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? y
- Were continuous integration tests run? If …
=> CASMPET-6514: Update ingresses to use CAN gateway

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/iuf/iuf-timing-dashboard.json, kubernetes/cray-sysmgmt-health/dashboards_json/kafka/kafka.json
_Minor dashboard fixes for IUF-timing and Kafka dashboard. Change is a backward-compatible bug fix._
* Resolves [CASMMON-300](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-300)
* `mug`
_Tested successfully_
- Fixed dashboards tested.
=> CASMMON-300 IUF-timing and kafka dashboard fix - release/1.4

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/iuf/iuf-timing-dashboard.json, kubernetes/cray-sysmgmt-health/dashboards_json/kafka/kafka.json
_Minor dashboard fixes for IUF-timing and Kafka dashboard. Change is a backward-compatible bug fix._
* Resolves [CASMMON-300](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-300)
* `mug`
_Tested successfully_
- Fixed dashboards tested.
=> CASMMON-300 IUF-timing and kafka dashboard fix

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/canu-test/deployment.yaml, kubernetes/cray-sysmgmt-health/templates/grok-exporter/deployment.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/disk-space/disk-space.yaml, kubernetes/cray-sysmgmt-health/templates/thanos/compactor/compactor-deployment.yaml, kubernetes/cray-sysmgmt-health/templates/thanos/querier/querier-deployment.yaml, kubernetes/cray-sysmgmt-health/templates/thanos/store/store-deployment.yaml, kubernetes/cray-sysmgmt-health/templates/thanos/upload-secret.yaml, kubernetes/cray-sysmgmt-health/values.yaml
* Resolves
https://jira-pro.it.hpe.com:8443/browse/CASMMON-323
https://jira-pro.it.hpe.com:8443/browse/CASMMON-321
Mug
Starlord
ncn-m001:/mnt/developer/sum/shreni/cray-sysmgmt-health/templates/canu-test # kubectl get pods -n sysmgmt-health                                                  NAME                                                            READY   STATUS      RESTARTS   AGE …
=> CASMMON-323 & CASMMON-321

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/thanos/upload-secret.yaml, kubernetes/cray-sysmgmt-health/values.yaml
* Resolves - https://jira-pro.it.hpe.com:8443/browse/CASMPET-6669
Mug
=> CASMPET-6669: sysmgmt: thanos has hard-coded S3 endpoint of "rgw-vip.nmn"

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/smartmon/smartmon.json
* Resolves: https://jira-pro.it.hpe.com:8443/browse/CASMMON-359
Starlord
=> CASMMON-359: Not getting UAN node metrics on grafana smartmon dashboard

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/kubernetes/apiserver.json, kubernetes/cray-sysmgmt-health/dashboards_json/kubernetes/k8s-resources-cluster.json, kubernetes/cray-sysmgmt-health/dashboards_json/kubernetes/prometheus.json
* Resolves - https://jira-pro.it.hpe.com:8443/browse/CASMMON-366
Drax
=> Casmmon 366 1.5

.github/workflows/charts-lint-test-scan.yml, kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/kubernetes/apiserver.json, kubernetes/cray-sysmgmt-health/dashboards_json/kubernetes/k8s-resources-cluster.json, kubernetes/cray-sysmgmt-health/dashboards_json/kubernetes/prometheus.json
* Resolves - https://jira-pro.it.hpe.com:8443/browse/CASMMON-366
Drax
=> Some of the grafana dashboard panels do not have data

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
* Resolves - https://jira-pro.it.hpe.com:8443/browse/CASMMON-373?filter=-1
Mug
=> CASMMON-373:Update node-exporter config to monitor snmp counters

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/kubernetes/persistentvolumesusage.json
* Resolves - https://jira-pro.it.hpe.com:8443/browse/CASMMON-374
On Mug
=> CASMMON-374-Restructure Persistent Volume Grafana dashboard

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/redfish-exporter/configmap.yaml
* Resolves 
* https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7063
=> Removed junk target

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/monitors/configmap.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/monitors/patch-service-monitors-job.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/monitors/rbac.yaml
spire certificate expiry needs prior warning to avoid heavy impact on system
https://jira-pro.it.hpe.com:8443/browse/CASMMON-409
ystem.yaml","concurrency":1},{"name":"kubernetes-system-apiserver","rules":[{"state":"inactive","name":"KubeClientCertificateExpiration","query":"apiserver_client_certificate_expiration_seconds_count{job=\"apiserver\"} \u003e 0 and on(job) histogram_quantile(0.01, sum by (job, le) (rate(apiserver_client_certificate_expiration_seconds_bucket{job=\"apiserver\"}[5m]))) \u003c 7776000","duration":300,"keep_firing_for":0,"labels":{"severity":"warning"},"annotations":{"description":"A client certificate used to authenticate to kubernetes apiserver is expiring in less than 90.0 …
=> spire certificate expiry needs prior warning to avoid heavy impact on system

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
#
CASMMON-418 Fix CVEs for vmalert:v1.93.1 and CASMMON-421 vminsert:v1.93.1-cluster
https://jira-pro.it.hpe.com:8443/browse/CASMMON-417
https://jira-pro.it.hpe.com:8443/browse/CASMMON-421
Mug
=> Fix CVEs for vmalert:v1.93.1 and CASMMON-421 vminsert:v1.93.1-cluster

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/redfish-exporter/configmap.yaml, kubernetes/cray-sysmgmt-health/values.yaml
_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?
* Resolves - https://jira-pro.it.hpe.com:8443/browse/CASM-4810
Mug
=> CASMMON-397: Retrieve SMART metrics from E1000 via redfish and send via prometheus

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/fluentbit/fluentbit.json, kubernetes/cray-sysmgmt-health/dashboards_json/kubernetes/k8s-coredns.json, kubernetes/cray-sysmgmt-health/dashboards_json/logstash/logstash.json, kubernetes/cray-sysmgmt-health/templates/grafana/configmap.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/monitors/configmap.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/monitors/fluentbit-aggregator.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/monitors/fluentbit-collector.yaml, kubernetes/cray-sysmgmt-health/values.yaml
CASMMON-440 Create VMscrape service for logstash , fluentbit grafana dashboards
[
* Merge with/before/after `<insert PR URL here>`](https://jira-pro.it.hpe.com:8443/browse/CASMMON-440)
starloard
=> CASMMON-440 Create VMscrape service for logstash , fluentbit grafana dashboards

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/fluentbit/fluentbit.json, kubernetes/cray-sysmgmt-health/values.yaml
CASMMON-440-VMscrape services and update resourecs
[
](https://jira-pro.it.hpe.com:8443/browse/CASMMON-440)
=> CASMMON-440-VMscrape services and update resourecs

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/migrated-rules/kube-scheduler.rules.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/migrated-rules/node-exporter.rules.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/migrated-rules/node.rules.yaml, kubernetes/cray-sysmgmt-health/values.yaml
* Resolves - https://jira-pro.it.hpe.com:8443/browse/CASMMON-441
=> CASMMON-441: Add VMRule records to solve grafana panel issues

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/templates/prometheus/monitors/strimzi-pod-monitor.yaml, kubernetes/cray-sysmgmt-health/values.yaml
fix VMscrape services
https://jira-pro.it.hpe.com:8443/browse/CASMMON-449
* `<development system>`
=> CASMMON-449

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/iscsi/iscsi.json, kubernetes/cray-sysmgmt-health/dashboards_json/kubernetes/k8s-resources-cluster.json, kubernetes/cray-sysmgmt-health/dashboards_json/snmp/nodenetwork.json, kubernetes/cray-sysmgmt-health/templates/grafana/configmap.yaml, kubernetes/cray-sysmgmt-health/values.yaml
* Resolves - https://jira-pro.it.hpe.com:8443/browse/CASMMON-410
=> Create a Grafana dashaboard for LIO metrics

kubernetes/cray-sysmgmt-health/Chart.yaml
=> CASMMON-458 version changes

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
[_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_
](https://jira-pro.it.hpe.com:8443/browse/CASMMON-458)
* `<development system>`
_How were the …
=> CASMMON-458 images issues

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
* Resolves - https://jira-pro.it.hpe.com:8443/browse/CASMMON-475
Tested on Drax
=> CASMMON-475

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
CASMMON-478 SNMP exporter for cray-sysmgmt-health upgrade
CASMMON-500 duplicates quay.io/prometheus/prometheus issue 
https://jira-pro.it.hpe.com:8443/browse/CASMMON-478
https://jira-pro.it.hpe.com:8443/browse/CASMMON-500
curl 10.31.254.219:9116/snmp?target=10.252.0.2
ifAdminStatus{ifAlias="",ifDescr="1/1/18",ifIndex="18",ifName="1/1/18"} 2
ifAdminStatus{ifAlias="",ifDescr="1/1/2",ifIndex="2",ifName="1/1/2"} 2
ifAdminStatus{ifAlias="",ifDescr="1/1/21",ifIndex="21",ifName="1/1/21"} 2
ifAdminStatus{ifAlias="",ifDescr="1/1/24",ifIndex="24",ifName="1/1/24"} 2
ifAdminStatus{ifAlias="",ifDescr="1/1/27",ifIndex="27",ifName="1/1/27"} 2
ifAdminStatus{ifAlias="",ifDescr="1/1/28",ifIndex="28",ifName="1/1/28"} 2 …
=> CASMMON-478 SNMP exporter upgrade

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/grok_exporter/greenlight-redlight.json
Upgrade grafana clusterview panel to 1.3.2 in SMH
* Resolves https://jira-pro.it.hpe.com:8443/browse/CASMMON-514
* tyr
=> CASMMON-514 Upgrade grafana clusterview panel to 1.3.2 in SMH

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/dashboards_json/flow/sma-flow-stats.json, kubernetes/cray-sysmgmt-health/dashboards_json/fluentbit/fluentbit.json, kubernetes/cray-sysmgmt-health/dashboards_json/grok_exporter/greenlight-redlight.json, kubernetes/cray-sysmgmt-health/dashboards_json/iscsi/iscsi.json, kubernetes/cray-sysmgmt-health/dashboards_json/kubernetes/k8s-resources-cluster.json, kubernetes/cray-sysmgmt-health/dashboards_json/logstash/logstash.json, kubernetes/cray-sysmgmt-health/dashboards_json/snmp/nodenetwork.json, kubernetes/cray-sysmgmt-health/dashboards_json/vm/operator.json, kubernetes/cray-sysmgmt-health/values.yaml
1. rename victorismetrics to VictoriaMetrics everywhere
2. Add uid "prometheus" to VictoriaMetrics datasource
3. Configure Flow Dashboard to use correct datasource(prometheus).
4. change PB894574A363DF0AF and P1EB0681B67ED710F to prometheus
=> Rectify Data Source Problems

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
Fix the missed version changes in Chart.yaml as a part of this PR https://github.com/Cray-HPE/cray-sysmgmt-health/pull/196
* Related to https://jira-pro.it.hpe.com:8443/browse/CASMMON-508
* wasp
=> CASMMON-508 Fix the missed version changes in Chart.yaml

kubernetes/cray-sysmgmt-health/Chart.yaml
* Resolves - https://jira-pro.it.hpe.com:8443/browse/CASMMON-536
* Drax
_How were the changes tested and success verified? If schema changes were part of this change, how were those …
=> CASMMON-536

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
* Resolves - https://jira-pro.it.hpe.com:8443/browse/CASMMON-537
Starlord
_How were the changes tested and success verified? If schema changes were part of this change, how were those …
=> CASMMON-537

kubernetes/cray-sysmgmt-health/Chart.yaml, kubernetes/cray-sysmgmt-health/values.yaml
cray-canu/canu-test:1.6.36 image has high vulnerabilities. Switch to a different image that uses the latest canu rpm's.
* Resolves CASMMON-552
* starlord
Latest image and pod logs
```
ncn-m001:/mnt/developer/akshar # kubectl get deployments.apps -n sysmgmt-health cray-sysmgmt-health-canu-test -o yaml | grep cray-canu
image: arti.hpc.amslabs.hpecorp.net/csm-docker-remote/stable/cray-canu/canu-test:2.0.1
ncn-m001:/mnt/developer/akshar # kubectl logs -n sysmgmt-health cray-sysmgmt-health-canu-test-6bc4458d9d-nk2lx 
Defaulted container "canu-test" out of: canu-test, grok
Performing canu test, check /logs/canu.log for output ...
Performing canu test, check /logs/canu.log for output ...
```
Latest rpm and canu.log
```
canu / : rpm -qa | grep canu
canu-2.0.1-1.x86_64
canu / : cat /logs/canu.log …
```
=> CASMMON-552 Review usage of cray-canu/canu-test:1.6.36 image and fix
